#language: shell
language: ruby
rvm:
 - 2.6
matrix:
env:
    - COVERAGE=1
    - COVERAGE=0
cache:
  directories:
    - $HOME/.m2/repository

before_install:
  - sudo apt-get update -qq

install:
  - gem install coveralls
  - gem install bashcov --version 1.8.2 --no-format-exec
  - gem regenerate_binstubs
  - sh -e misc/ci-setup.sh

script:
  - sh -e misc/ci-runtest.sh
